server:
  port: 8080

spring:
  application:
    name: grok
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hierarchy:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            enabled: true
            initialize-schema: always # Tells Spring AI to spin up default behaviors
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: ${GROK-API-KEY}
      chat:
        model: openai/gpt-oss-120b
        temperature: 0.5
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: always
      chat:
        model: llama3.2:1b # Use llama3.2:1b or llama3.2:3b if preferred
        temperature: 0.7 # Controls response creativity
        top-p: 0.9 #

logging:
  level:
    root: INFO
    org.springframework.ai.chat.client.advisor: DEBUG
