server:
  port: 8080

spring:
  application:
    name: grok
  ai:
    chat:
      client:
        enabled: false
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: {GROK-API-KEY}
      chat:
        model: openai/gpt-oss-120b
        temperature: 1
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: always
      chat:
        model: llama3.2:1b # Use llama3.2:1b or llama3.2:3b if preferred
        temperature: 0.7 # Controls response creativity
        top-p: 0.9 #

logging:
  level:
    root: INFO
    org.springframework.ai.chat.client.advisor: DEBUG
